openapi: 3.2.0
info:
  description: 'The Outdoorsy API (or simply "API") is organized around REST. It uses

    predictable, resource-oriented URLs and implements standard HTTP response

    codes, verbs, authentication mechanisms, and a variety of request encodings.


    ## Versioning


    The API implements semantic versioning.'
  title: Outdoorsy API Documentation Bundle Features API
  version: 0.0.1
servers:
- url: /v0
security:
- Bearer:
  - '[]'
- API-Key:
  - '[]'
tags:
- name: bundleFeatures
paths:
  /bundles/{bundle_id}/features:
    post:
      description: Create a bundle feature
      tags:
      - bundleFeatures
      operationId: createBundleFeature
      responses:
        '201':
          $ref: '#/components/responses/bundleFeatureResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '404':
          $ref: '#/components/responses/notFoundError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BundleFeature'
  /bundles/{bundle_id}/features/{id}:
    get:
      description: Retrieve bundle feature by id
      tags:
      - bundleFeatures
      operationId: getBundleFeatureById
      parameters:
      - x-go-name: BundleID
        name: bundle_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - x-go-name: ID
        name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          $ref: '#/components/responses/bundleFeatureResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '404':
          $ref: '#/components/responses/notFoundError'
    delete:
      description: Delete bundle feature
      tags:
      - bundleFeatures
      operationId: deleteBundleFeature
      parameters:
      - x-go-name: BundleID
        name: bundle_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - x-go-name: ID
        name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          $ref: '#/components/responses/noContentResponse'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '404':
          $ref: '#/components/responses/notFoundError'
    patch:
      description: Update bundle feature
      tags:
      - bundleFeatures
      operationId: updateBundleFeature
      parameters:
      - x-go-name: BundleID
        name: bundle_id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - x-go-name: ID
        name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          $ref: '#/components/responses/bundleFeatureResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorizedError'
        '404':
          $ref: '#/components/responses/notFoundError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BundleFeature'
components:
  responses:
    notFoundError:
      description: Not found error
    bundleFeatureResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BundleFeature'
    badRequestError:
      description: Invalid input or state means you're bad
      headers:
        Error:
          schema:
            type: string
    noContentResponse:
      description: Everything went as planned
    unauthorizedError:
      description: Unauthorized error
  schemas:
    BundleFeature:
      type: object
      properties:
        bundle_id:
          type: string
          x-go-name: BundleID
        category:
          type: string
          x-go-name: Category
        created:
          type: string
          x-go-name: Created
          x-go-type: github.com/outdoorsy/api/clocks.RfcTime
        details:
          type: string
          x-go-name: Details
        id:
          type: string
          x-go-name: ID
        name:
          type: string
          x-go-name: Name
        position:
          type: integer
          format: int64
          x-go-name: Position
        regions:
          $ref: '#/components/schemas/DBStringSlice'
        service_id:
          type:
          - integer
          - 'null'
          format: int64
        type:
          type: string
          x-go-name: Type
        updated:
          type: string
          x-go-name: Updated
          x-go-type: github.com/outdoorsy/api/clocks.RfcTime
      x-go-package: github.com/outdoorsy/api/internal/bundle
    DBStringSlice:
      description: DBStringSlice is a []string with database conversion methods
      type: array
      items:
        type: string
      x-go-package: github.com/outdoorsy/api/utils
  securitySchemes:
    API-Key:
      type: apiKey
      name: API-Key
      in: header
    Bearer:
      type: apiKey
      name: Authorization
      in: header
